#ifndef SETTINGS_H
#define SETTINGS_H

//Constants governing position of stuff on screen
#define ROWS 32
#define COLUMNS 49
#define XOFF 23
#define YOFF 107
#define SQWID 20

//Constants defining colors of various things
#define WHITE 15
#define RED 4
#define PURPLE 5
#define GREEN 2
#define PINK 13
#define GREY 8
#define BLACK 0
#define GRIDCOLOR GREY
#define SQCOLOR PURPLE
#define BGCOLOR BLACK
#define SELCOLOR GREEN

#endif
